name: Generate ASCII workflow

on:
  push:
  #   paths:
  #     - '02.Executing_Shell_Script/**'
  # pull_request:
  #   paths:
  #     - '02.Executing_Shell_Script/**'

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List Repo Files
        run: ls -ltra

      - name: Execute Shell Script
        # working-directory: 02.Executing_Shell_Script
        run: ./ascii-script.sh
