name: Run ASCII Script

on:
  push:
    paths:
      - '02.Executing_Shell_Script/**'
  pull_request:
    paths:
      - '02.Executing_Shell_Script/**'

jobs:
  ascii_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Run ASCII Script
        working-directory: 02.Executing_Shell_Script
        run: ./ascii-script.sh

